### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by nadecancode** [cse110-sp24-group35/warmup-exercise#2]
Implementation: https://github.com/cse110-sp24-group35/warmup-exercise/issues/12

## User Story
As a person who manages multiple tasks in different priorities, I would like to let more important tasks have higher visibility.
As a person who oversees tasks in different topics, I would like to be able to group them by their topic.

## Features
- [x] Ability to sort the entries by deadline (https://github.com/cse110-sp24-group35/warmup-exercise/issues/6)
- [x]  (https://github.com/cse110-sp24-group35/warmup-exercise/issues/7)
- [ ]  (https://github.com/cse110-sp24-group35/warmup-exercise/issues/8)
- [x]  (https://github.com/cse110-sp24-group35/warmup-exercise/issues/9)
- [x]  (https://github.com/cse110-sp24-group35/warmup-exercise/issues/10)
- [x] (https://github.com/cse110-sp24-group35/warmup-exercise/issues/12)

## Roles
Designer - @ethanlee7102 @tylercooksrice 
Programmer - @Ant044 @ShotaYasuraoka @jxnxthxnz @mbizzigotti

## Diagram
[here](https://miro.com/app/board/uXjVKRKs4WE=/?share_link_id=95317501309)
